//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalEmploymentTest.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgFavorite
    {
        public int? IdImg { get; set; }
        public bool value { get; set; }
    }
}
